/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtucarriere.gui;

import java.awt.FlowLayout;

/**
 *
 * @author maximemivilledeschenes
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauPermanent = new javax.swing.JPanel();
        permanentPanel = new javax.swing.JTabbedPane();
        panelPlan = new javax.swing.JPanel();
        buttonAjouternoeud = new javax.swing.JToggleButton();
        buttonAjouterArc = new javax.swing.JToggleButton();
        buttonAjouterConcasseur = new javax.swing.JToggleButton();
        buttonAjouterCrible = new javax.swing.JToggleButton();
        buttonAjouterEntree = new javax.swing.JToggleButton();
        buttonAjouterTas = new javax.swing.JToggleButton();
        buttonAjouterBroyeur = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        buttonAjouterConvoyeur = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelSimulation = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        buttonTopPanel = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        toggleSelection = new javax.swing.JToggleButton();
        mainScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichierMenu = new javax.swing.JMenu();
        menuNouveauProjet = new javax.swing.JMenuItem();
        menuOuvrirProjet = new javax.swing.JMenuItem();
        menuSauvegarderProjet = new javax.swing.JMenuItem();
        menuSauvegarderSous = new javax.swing.JMenuItem();
        menuQuitter = new javax.swing.JMenuItem();
        editionMenu = new javax.swing.JMenu();
        menuUndo = new javax.swing.JMenuItem();
        menuRedo = new javax.swing.JMenuItem();
        menuCopier = new javax.swing.JMenuItem();
        menuColler = new javax.swing.JMenuItem();
        menuCouper = new javax.swing.JMenuItem();
        affichageMenu = new javax.swing.JMenu();
        menuZoomer = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        insererMenu = new javax.swing.JMenu();
        fenetreMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneauPermanent.setAlignmentY(1.0F);

        permanentPanel.setToolTipText("");
        permanentPanel.setAlignmentY(1.0F);
        permanentPanel.setAutoscrolls(true);
        permanentPanel.setMinimumSize(new java.awt.Dimension(111, 100));
        permanentPanel.setName(""); // NOI18N
        permanentPanel.setPreferredSize(new java.awt.Dimension(338, 950));

        panelPlan.setAutoscrolls(true);

        buttonAjouternoeud.setText("Ajouter un noeud");
        buttonAjouternoeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouternoeudActionPerformed(evt);
            }
        });

        buttonAjouterArc.setText("Ajouter un arc");
        buttonAjouterArc.setToolTipText("");
        buttonAjouterArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterArcActionPerformed(evt);
            }
        });

        buttonAjouterConcasseur.setText("Ajouter un concasseur");
        buttonAjouterConcasseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterConcasseurActionPerformed(evt);
            }
        });

        buttonAjouterCrible.setText("Ajouter un crible");

        buttonAjouterEntree.setText("Ajouter une entrée");

        buttonAjouterTas.setText("Ajouter un tas");

        buttonAjouterBroyeur.setText("Ajouter un broyeur");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Ajouter un élément");

        buttonAjouterConvoyeur.setText("Ajouter un convoyeur");
        buttonAjouterConvoyeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterConvoyeurActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Supprimer un élément");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Noeud1", "Arc1", "Noeud2", "Tas1", "Arc2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Noeud1", "Arc1", "Noeud2", "Tas1", "Arc2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Modifier un élément");

        jButton2.setText("Modifier");

        jButton3.setText("Supprimer");

        javax.swing.GroupLayout panelPlanLayout = new javax.swing.GroupLayout(panelPlan);
        panelPlan.setLayout(panelPlanLayout);
        panelPlanLayout.setHorizontalGroup(
            panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(253, 253, 253))
            .addGroup(panelPlanLayout.createSequentialGroup()
                .addGroup(panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPlanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(panelPlanLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttonAjouternoeud, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAjouterArc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAjouterConcasseur)
                                    .addComponent(buttonAjouterCrible, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAjouterEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAjouterTas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAjouterBroyeur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonAjouterConvoyeur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelPlanLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPlanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlanLayout.setVerticalGroup(
            panelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouternoeud)
                .addGap(4, 4, 4)
                .addComponent(buttonAjouterArc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouterConcasseur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouterCrible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouterEntree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouterTas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouterBroyeur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAjouterConvoyeur)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        permanentPanel.addTab("Plan", panelPlan);

        jButton1.setText("Créer une simulation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSimulationLayout = new javax.swing.GroupLayout(panelSimulation);
        panelSimulation.setLayout(panelSimulationLayout);
        panelSimulationLayout.setHorizontalGroup(
            panelSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSimulationLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
        );
        panelSimulationLayout.setVerticalGroup(
            panelSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimulationLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(831, Short.MAX_VALUE))
        );

        permanentPanel.addTab("Simulation", panelSimulation);

        panneauPermanent.add(permanentPanel);
        permanentPanel.getAccessibleContext().setAccessibleName("Plan");

        buttonTopPanel.setPreferredSize(new java.awt.Dimension(400, 35));

        toggleSelection.setText("Sélection");
        buttonTopPanel.add(toggleSelection);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScrollPane)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(buttonTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScrollPane)
                .addContainerGap())
        );

        fichierMenu.setText("Fichier");

        menuNouveauProjet.setText("Nouveau projet");
        menuNouveauProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNouveauProjetActionPerformed(evt);
            }
        });
        fichierMenu.add(menuNouveauProjet);

        menuOuvrirProjet.setText("Ouvrir un projet");
        fichierMenu.add(menuOuvrirProjet);

        menuSauvegarderProjet.setText("Sauvegarder");
        fichierMenu.add(menuSauvegarderProjet);

        menuSauvegarderSous.setText("Sauvegarder sous...");
        fichierMenu.add(menuSauvegarderSous);

        menuQuitter.setText("Quitter");
        menuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitterActionPerformed(evt);
            }
        });
        fichierMenu.add(menuQuitter);

        jMenuBar1.add(fichierMenu);

        editionMenu.setText("Édition");

        menuUndo.setText("Undo");
        editionMenu.add(menuUndo);

        menuRedo.setText("Redo");
        editionMenu.add(menuRedo);

        menuCopier.setText("Copier");
        editionMenu.add(menuCopier);

        menuColler.setText("Coller");
        editionMenu.add(menuColler);

        menuCouper.setText("Couper");
        editionMenu.add(menuCouper);

        jMenuBar1.add(editionMenu);

        affichageMenu.setText("Affichage");

        menuZoomer.setText("Zoomer");
        affichageMenu.add(menuZoomer);

        jMenuItem6.setText("Dézoomer");
        affichageMenu.add(jMenuItem6);

        jMenuItem1.setText("Grille magnétique");
        affichageMenu.add(jMenuItem1);

        jMenuBar1.add(affichageMenu);

        insererMenu.setText("Insérer");
        jMenuBar1.add(insererMenu);

        fenetreMenu.setText("Fenêtre");
        jMenuBar1.add(fenetreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panneauPermanent, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauPermanent, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNouveauProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNouveauProjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNouveauProjetActionPerformed

    private void menuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuQuitterActionPerformed

    private void buttonAjouternoeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouternoeudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjouternoeudActionPerformed

    private void buttonAjouterArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterArcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjouterArcActionPerformed

    private void buttonAjouterConcasseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterConcasseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjouterConcasseurActionPerformed

    private void buttonAjouterConvoyeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterConvoyeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjouterConvoyeurActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu affichageMenu;
    private javax.swing.JToggleButton buttonAjouterArc;
    private javax.swing.JToggleButton buttonAjouterBroyeur;
    private javax.swing.JToggleButton buttonAjouterConcasseur;
    private javax.swing.JToggleButton buttonAjouterConvoyeur;
    private javax.swing.JToggleButton buttonAjouterCrible;
    private javax.swing.JToggleButton buttonAjouterEntree;
    private javax.swing.JToggleButton buttonAjouterTas;
    private javax.swing.JToggleButton buttonAjouternoeud;
    private javax.swing.JPanel buttonTopPanel;
    private javax.swing.JMenu editionMenu;
    private javax.swing.JMenu fenetreMenu;
    private javax.swing.JMenu fichierMenu;
    private javax.swing.JMenu insererMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JMenuItem menuColler;
    private javax.swing.JMenuItem menuCopier;
    private javax.swing.JMenuItem menuCouper;
    private javax.swing.JMenuItem menuNouveauProjet;
    private javax.swing.JMenuItem menuOuvrirProjet;
    private javax.swing.JMenuItem menuQuitter;
    private javax.swing.JMenuItem menuRedo;
    private javax.swing.JMenuItem menuSauvegarderProjet;
    private javax.swing.JMenuItem menuSauvegarderSous;
    private javax.swing.JMenuItem menuUndo;
    private javax.swing.JMenuItem menuZoomer;
    private javax.swing.JPanel panelPlan;
    private javax.swing.JPanel panelSimulation;
    private javax.swing.JPanel panneauPermanent;
    private javax.swing.JTabbedPane permanentPanel;
    private javax.swing.JToggleButton toggleSelection;
    // End of variables declaration//GEN-END:variables
}
