/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtucarriere.gui;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import virtucarriere.Domaine.Controller.Controller;
import virtucarriere.Domaine.Controller.Controller.EquipementModes;

public class MainWindow extends JFrame {
    
    public Controller controller;
    
    public EquipementModes selectedEquipementMode;

    private MeasurementUnitMode currentMeasurementUnitMode = MeasurementUnitMode.METRIC;
    private ApplicationMode currentApplicationMode = ApplicationMode.SELECT;

    public Point currentMousePoint = new Point();
    public Point initMousePoint = new Point();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        controller = new Controller();
        initComponents();
       // setFocusable(true);
    }
    
    public void setMode(EquipementModes newMode) {
        this.selectedEquipementMode = newMode;
    }

    public enum MeasurementUnitMode {
        METRIC, IMPERIAL
    }

    public enum ApplicationMode {
        SELECT, ADD_PLAN, ADD_SIMULATION
    }

    public MeasurementUnitMode getCurrentMeasurementUnitMode() {
        return currentMeasurementUnitMode;
    }

    public void setCurrentMeasurementUnitMode(MeasurementUnitMode newMeasurementUnitMode) {
        this.currentMeasurementUnitMode = newMeasurementUnitMode;
    }

    public void setCurrentApplicationMode(ApplicationMode newApplicationMode) {
        this.currentApplicationMode = newApplicationMode;
    }

    public DrawingPanel getDrawingPanel() {
        return this.drawingPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonTopPanel = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        jToggleButton1 = new javax.swing.JToggleButton();
        mainScrollPane = new javax.swing.JScrollPane();
        drawingPanel = new virtucarriere.gui.DrawingPanel(this);
        jPanel1 = new javax.swing.JPanel();
        AddBroyeur = new javax.swing.JButton();
        addConcasseur = new javax.swing.JButton();
        addCrible = new javax.swing.JButton();
        addConvoyeur = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichierMenu = new javax.swing.JMenu();
        menuNouveauProjet = new javax.swing.JMenuItem();
        menuOuvrirProjet = new javax.swing.JMenuItem();
        menuSauvegarderProjet = new javax.swing.JMenuItem();
        menuSauvegarderSous = new javax.swing.JMenuItem();
        menuQuitter = new javax.swing.JMenuItem();
        editionMenu = new javax.swing.JMenu();
        menuUndo = new javax.swing.JMenuItem();
        menuRedo = new javax.swing.JMenuItem();
        menuCopier = new javax.swing.JMenuItem();
        menuColler = new javax.swing.JMenuItem();
        menuCouper = new javax.swing.JMenuItem();
        affichageMenu = new javax.swing.JMenu();
        menuZoomer = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuAffichageGrille = new javax.swing.JMenuItem();
        importerMenu = new javax.swing.JMenu();
        importerCarriereMenu = new javax.swing.JMenuItem();
        importerSimulationMenu = new javax.swing.JMenuItem();
        fenetreMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        buttonTopPanel.setToolTipText("");
        buttonTopPanel.setPreferredSize(new java.awt.Dimension(1410, 35));

        jToggleButton1.setText("SELECT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        buttonTopPanel.add(jToggleButton1);

        mainPanel.add(buttonTopPanel, java.awt.BorderLayout.NORTH);

        mainScrollPane.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mainScrollPaneMouseWheelMoved(evt);
            }
        });

        drawingPanel.setOpaque(false);
        drawingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawingPanelMousePressed(evt);
            }
        });
        drawingPanel.setLayout(new java.awt.BorderLayout());
        mainScrollPane.setViewportView(drawingPanel);

        mainPanel.add(mainScrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 765));

        AddBroyeur.setText("Ajout Broyeur");
        AddBroyeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBroyeurActionPerformed(evt);
            }
        });

        addConcasseur.setText("Ajout Concasseur");
        addConcasseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConcasseurActionPerformed(evt);
            }
        });

        addCrible.setText("Ajout Crible");
        addCrible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCribleActionPerformed(evt);
            }
        });

        addConvoyeur.setText("Ajout Convoyeur");
        addConvoyeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConvoyeurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(addCrible)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBroyeur)
                    .addComponent(addConcasseur))
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addConvoyeur)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(AddBroyeur)
                .addGap(49, 49, 49)
                .addComponent(addConcasseur)
                .addGap(64, 64, 64)
                .addComponent(addCrible)
                .addContainerGap(497, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addConvoyeur)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(jPanel1, java.awt.BorderLayout.EAST);

        fichierMenu.setText("Fichier");

        menuNouveauProjet.setText("Nouveau projet");
        menuNouveauProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNouveauProjetActionPerformed(evt);
            }
        });
        fichierMenu.add(menuNouveauProjet);

        menuOuvrirProjet.setText("Ouvrir un projet");
        fichierMenu.add(menuOuvrirProjet);

        menuSauvegarderProjet.setText("Sauvegarder");
        fichierMenu.add(menuSauvegarderProjet);

        menuSauvegarderSous.setText("Sauvegarder sous...");
        fichierMenu.add(menuSauvegarderSous);

        menuQuitter.setText("Quitter");
        menuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitterActionPerformed(evt);
            }
        });
        fichierMenu.add(menuQuitter);

        jMenuBar1.add(fichierMenu);

        editionMenu.setText("Édition");

        menuUndo.setText("Undo");
        editionMenu.add(menuUndo);

        menuRedo.setText("Redo");
        editionMenu.add(menuRedo);

        menuCopier.setText("Copier");
        editionMenu.add(menuCopier);

        menuColler.setText("Coller");
        editionMenu.add(menuColler);

        menuCouper.setText("Couper");
        editionMenu.add(menuCouper);

        jMenuBar1.add(editionMenu);

        affichageMenu.setText("Affichage");

        menuZoomer.setText("Zoomer");
        affichageMenu.add(menuZoomer);

        jMenuItem6.setText("Dézoomer");
        affichageMenu.add(jMenuItem6);

        menuAffichageGrille.setText("Grille magnétique");
        menuAffichageGrille.setSelected(drawingPanel.getGridlines());
        menuAffichageGrille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAffichageGrilleMouseClicked(evt);
            }
        });
        menuAffichageGrille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAffichageGrilleActionPerformed(evt);
            }
        });
        affichageMenu.add(menuAffichageGrille);

        jMenuBar1.add(affichageMenu);

        importerMenu.setText("Importer");
        importerMenu.setToolTipText("");

        importerCarriereMenu.setText("Importer une carrière");
        importerMenu.add(importerCarriereMenu);

        importerSimulationMenu.setText("Importer une simulation");
        importerMenu.add(importerSimulationMenu);

        jMenuBar1.add(importerMenu);

        fenetreMenu.setText("Fenêtre");
        jMenuBar1.add(fenetreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void AddBroyeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBroyeurActionPerformed
        // TODO add your handling code here:
        this.setMode(EquipementModes.BROYEUR);
    }//GEN-LAST:event_AddBroyeurActionPerformed

    private void addConcasseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConcasseurActionPerformed
        this.setMode(EquipementModes.CONCASSEUR);
    }//GEN-LAST:event_addConcasseurActionPerformed

    private void addCribleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCribleActionPerformed
       this.setMode(EquipementModes.CRIBLE);
    }//GEN-LAST:event_addCribleActionPerformed

    private void addConvoyeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConvoyeurActionPerformed
        // TODO add your handling code here:
        this.setMode(EquipementModes.CONVOYEUR);
    }//GEN-LAST:event_addConvoyeurActionPerformed

    private void drawingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawingPanelMousePressed
        Point mousePoint = evt.getPoint();
        Controller.EquipementModes actualEquipement = this.selectedEquipementMode;
        this.controller.addEquipement(actualEquipement, mousePoint);
        drawingPanel.repaint();
    }//GEN-LAST:event_drawingPanelMousePressed

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        Point point = evt.getPoint();
        this.currentMousePoint = evt.getPoint();
        if(evt.getPreciseWheelRotation() > 0){
            drawingPanel.zoomIn(point);
        }
        else{
            drawingPanel.zoomOut(point);
        }
    }//GEN-LAST:event_formMouseWheelMoved

    private void mainScrollPaneMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mainScrollPaneMouseWheelMoved
        Point point = evt.getPoint();
        this.currentMousePoint = evt.getPoint();
        if(evt.getPreciseWheelRotation() > 0){
            drawingPanel.zoomIn(point);
        }
        else{
            drawingPanel.zoomOut(point);
        }
    }//GEN-LAST:event_mainScrollPaneMouseWheelMoved

    private void menuNouveauProjetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuNouveauProjetActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_menuNouveauProjetActionPerformed

    private void menuQuitterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuQuitterActionPerformed
        System.exit(0);
    }// GEN-LAST:event_menuQuitterActionPerformed

    private void buttonAjouterNoeudActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonAjouterNoeudActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonAjouterNoeudActionPerformed

    private void buttonAjouterArcActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonAjouterArcActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonAjouterArcActionPerformed

    private void buttonAjouterConcasseurActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonAjouterConcasseurActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonAjouterConcasseurActionPerformed

    private void buttonAjouterConvoyeurActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonAjouterConvoyeurActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonAjouterConvoyeurActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton4ActionPerformed

    private void menuAffichageGrilleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuAffichageGrilleActionPerformed
        drawingPanel.setGridLines();
    }// GEN-LAST:event_menuAffichageGrilleActionPerformed

    private void menuAffichageGrilleMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuAffichageGrilleMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_menuAffichageGrilleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    public Dimension getMainScrollPaneDimension() {
        return mainScrollPane.getSize();
    }

    public JScrollPane getMainScrollPane() {
        return this.mainScrollPane;
    }

    public void setMainScrollPanePosition(Point point) {
        this.mainScrollPane.getViewport().setViewPosition(point);
    }

    public void draw(Graphics2D g, DrawingPanel drawingPanel, double zoom) {
       // controller.draw(g, getCurrentMeasurementUnitMode(), drawingPanel, zoom, currentMousePoint);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBroyeur;
    private javax.swing.JButton addConcasseur;
    private javax.swing.JButton addConvoyeur;
    private javax.swing.JButton addCrible;
    private javax.swing.JMenu affichageMenu;
    private javax.swing.JPanel buttonTopPanel;
    private virtucarriere.gui.DrawingPanel drawingPanel;
    private javax.swing.JMenu editionMenu;
    private javax.swing.JMenu fenetreMenu;
    private javax.swing.JMenu fichierMenu;
    private javax.swing.JMenuItem importerCarriereMenu;
    private javax.swing.JMenu importerMenu;
    private javax.swing.JMenuItem importerSimulationMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JMenuItem menuAffichageGrille;
    private javax.swing.JMenuItem menuColler;
    private javax.swing.JMenuItem menuCopier;
    private javax.swing.JMenuItem menuCouper;
    private javax.swing.JMenuItem menuNouveauProjet;
    private javax.swing.JMenuItem menuOuvrirProjet;
    private javax.swing.JMenuItem menuQuitter;
    private javax.swing.JMenuItem menuRedo;
    private javax.swing.JMenuItem menuSauvegarderProjet;
    private javax.swing.JMenuItem menuSauvegarderSous;
    private javax.swing.JMenuItem menuUndo;
    private javax.swing.JMenuItem menuZoomer;
    // End of variables declaration//GEN-END:variables
}
